### ISSUE TITLE
Only process historical blocks for which Warp is activated

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#129]
**Context and scope**
Any block range may be processed on startup, depending on the state of the DB and the `StartBlockHeight` configuration option, added in https://github.com/ava-labs/awm-relayer/pull/114. However, there's no need to query blocks for which Warp is not activated, so we should filter that range.

**Discussion and alternatives**
https://github.com/ava-labs/awm-relayer/pull/124 and https://github.com/ava-labs/subnet-evm/pull/1040 allow the relayer to fetch a chain's Warp config via `ethclient.ChainConfig`. We should use this to fetch the Warp config on the source chain to get the lowest block at which Warp is enabled. We can then set that as a floor for processing historical blocks.

**Comment by michaelkaplan13** [comment]
Closing this out for now since it hasn't been an issue to date, and an easy workaround if it ever is an issue for someone is to set the starting block height to a more recent block and restart the relayer.
