### ISSUE TITLE
Relayer should process historical blocks first.

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/awm-relayer#138]
**Context and scope**
Currently the relayer goroutines will call `forwardLogs()` when first setting up the subscription, causing new logs to be sent to `logsChan` before any historical logs are processed. If the relayer crashes, or the context is cancelled by another relayer coroutine, we may process a new log and write that log's block height to the database. On restart, we will then process from the blockheight in the db, skipping any historical logs that were missed.

**Discussion and alternatives**
Any solution here should also take into account reconnections. Currently, the `forwardLogs()` goroutine will persist even when the subscriber disconnects, so it could lead to new blocks being processed before missed blocks after a reconnection. We should try our best to process logs in block-order so that there is no chance of a database discrepancy.

**Comment by cam-schultz** [comment]
Fixed by https://github.com/ava-labs/awm-relayer/pull/140
