### ISSUE TITLE
Process Logs while processing historical blocks

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/awm-relayer#139]
**Context and scope**
We currently process historical blocks synchronously, which only adds any relevant transactions to a channel. The channel is only processed once we have finished looking at all the historical blocks. We should be consuming the channel at the same time that we're adding to it, or we could end up in a deadlock.

**Discussion and alternatives**
A deadlock here is unlikely in the near-term, since the channel capacity is 20000, and we would need to fill that for a deadlock, but currently if the application crashes or errors while we're adding all the historical transactions to the channel, all progress will be lost. If we consume these transactions at the same time, we will be able to pick up where we left off after a restart.

**Comment by cam-schultz** [comment]
Fixed by https://github.com/ava-labs/awm-relayer/pull/140
