### ISSUE TITLE
Specify manual Warp messages by ID

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#171]
**Context and scope**
https://github.com/ava-labs/awm-relayer/pull/153 introduced manual Warp messages provided by the relayer config. The full unsigned message bytes must be specified.

As of `v1.11.0-fuji`, avalanchego supports the `GetMessage` endpoint in the Warp API, so we should be able to specify only the Warp message ID, and fetch the unsigned message bytes from the API node. The Warp message ID is of fixed size, whereas a Warp message may be of unbounded size, so we should definitely use the ID in the configuration.

**Comment by michaelkaplan13** [comment]
@cam-schultz / @geoff-vball  Can this issue be closed now that #314 is completed?

**Comment by cam-schultz** [comment]
> @cam-schultz / @geoff-vball Can this issue be closed now that #314 is completed?

Yes indeed 👍
