### ISSUE TITLE
Support query parameters and HTTP headers for API requests

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#186]
**Context and scope**
The relayer makes RPC requests to a handful of Avalanche APIs via the Golang clients. Specifically, the relayer uses:
- [platformvm.Client](https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/client.go#L27)
- [info.Client](https://github.com/ava-labs/avalanchego/blob/master/api/info/client.go#L19)

These clients support HTTP headers and query parameters in the form of the optional `rpc.Option` parameters to each of their method calls.

We should add `query-parameters` and `http-headers` fields to the top-level config to support these options. This would allow us to provide a rate limit bypass token, for example.

The relayer also uses [ethclient.Client](https://github.com/ava-labs/subnet-evm/blob/master/ethclient/ethclient.go#L70), which supports query parameters in the form of a fully specified URL. HTTP headers are supported via `rpc.Client.SetHeader`. It might make sense to add a `query-parameters` field to the `source-subnets` and `destination-subnets` lists for consistency.

**Comment by najeal** [comment]
Hi @cam-schultz , please assign it to me.

The values provided by the new fields need to be passed to every requests right?

**Comment by cam-schultz** [comment]
Hey @najeal, thanks for offering to take a look at this. @minghinmatthewlam is going to take an initial pass at this to support query parameters for `p-chain-api-url` and `info-api-url` to reach parity with the subnet RPC and WS API fields.

Please feel free to open a PR with any further proposed changes. To close this ticket out, we'll also need to support HTTP headers provided via configuration.

> The values provided by the new fields need to be passed to every requests right?

For the [Info API and P-Chain API](https://github.com/ava-labs/awm-relayer/blob/main/main/main.go#L74-L75) calls, this is correct. The [subnet RPC API](https://github.com/ava-labs/awm-relayer/blob/main/vms/evm/destination_client.go#L51) takes a raw URL, so query parameters are directly supported. Further investigation needs to be done for supporting HTTP headers for subnet RPC calls.

**Comment by najeal** [comment]
@cam-schultz thank for the answer.
This means I need to wait for @minghinmatthewlam PR that will partially resolve the issue, then I can complete the rest?

**Comment by cam-schultz** [comment]
@najeal, yes that would be great. Appreciate your patience on this 🙏
