### ISSUE TITLE
Validate peer version

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#193]
**Context and scope**
If there is a peer mismatch between the relayer and subnet validators, then app requests to fetch signatures will fail. We should explicitly check peer compatibility on startup to more clearly signal a mismatch.

**Discussion and alternatives**
The check should take into consideration the subnet's Warp stake threshold. For example, if a subnet's Warp quorum numerator is 67, then we only need 67% of validator peers to be reachable.

**Open questions**
There's no RPC to fetch the peer version directly, so we'll need to decide the best way to detect a mismatch. Some ideas:
- Count P2P connection errors
- Fetch the node version from the info API, and compare against the minor version run by the relayer (bug fix versions should all be compatible)

**Comment by felipemadero** [comment]
In relation with CLI, it may be also desirable to give CLI or other automating tools a way to decide on the compatibility of a given relayer with a given avalanchego. Subnet-evm has something like this here https://github.com/ava-labs/subnet-evm/blob/master/compatibility.json which we can use together with https://github.com/ava-labs/avalanchego/blob/master/version/compatibility.json to decide which avago to use in relation with a given subnet.
In the same direction, we may want to know which relayer to use in relation with a given avago version, so maybe you can add a compability file to your repo with the map between relayer and avago versions.

**Comment by cam-schultz** [comment]
> In relation with CLI, it may be also desirable to give CLI or other automation tools a way to decide on the compatibility of a given relayer with a given avalanchego. Subnet-evm has something like this here https://github.com/ava-labs/subnet-evm/blob/master/compatibility.json which we can use together with https://github.com/ava-labs/avalanchego/blob/master/version/compatibility.json to decide which avago to use in relation with a given vm. In the same direction, we may want to know which relayer to use in relation with a given avago version, so maybe you can add a compability file to your repo with the map between relayer and avago versions.

I agree it should be possible to do this filtering ahead of runtime. Rather than a compatibility manifest, we should be able to use the avalanchego dependency version in go.mod to determine compatibility. The relayer's P2P networking layer is built on top of tooling hosted in avalanchego, so the problem is the same as determining if a given avalanchego node is compatible at the P2P layer with its peers.

I'd like to maintain a single source of truth regarding dependencies as much as possible.

**Comment by felipemadero** [comment]
> > In relation with CLI, it may be also desirable to give CLI or other automation tools a way to decide on the compatibility of a given relayer with a given avalanchego. Subnet-evm has something like this here https://github.com/ava-labs/subnet-evm/blob/master/compatibility.json which we can use together with https://github.com/ava-labs/avalanchego/blob/master/version/compatibility.json to decide which avago to use in relation with a given vm. In the same direction, we may want to know which relayer to use in relation with a given avago version, so maybe you can add a compability file to your repo with the map between relayer and avago versions.
> 
> I agree it should be possible to do this filtering ahead of runtime. Rather than a compatibility manifest, we should be able to use the avalanchego dependency version in go.mod to determine compatibility. The relayer's P2P networking layer is built on top of tooling hosted in avalanchego, so the problem is the same as determining if a given avalanchego node is compatible at the P2P layer with its peers.
> 
> I'd like to maintain a single source of truth regarding dependencies as much as possible.

I believe the go.mod dependency is a 1-to-1 map from relayer to avago, and most probably not enough to do a full mapping from any recently released avalanchego version to the corresponding relayer. Are you suggesting to iterate over all relayer versions at runtime, check each go.mod, add the pair to a map, and then try to infer needed relayer for any recent avago? I believe some hand work job may be needed.

**Comment by cam-schultz** [comment]
Avalanchego peers are compatible with one another, as long as the minor version matches. We can therefore tell just by looking at `awm-relayer`'s go.mod which Avalanchego versions it is compatible with. A manifest in `awm-relayer` would be redundant. 

If `avalanche-cli`'s consumption of `awm-relayer` would be simplified by maintaining a manifest, then it should be checked into `avalanche-cli` rather than `awm-relayer`.

**Comment by cam-schultz** [comment]
Shifting back to the implementation of this check in the relayer, I think the only way would be to count P2P connection errors on startup, since there's no guarantee that peers will have their info API enabled. If enough peers are on an incompatible version, we should refuse to startup.

In any case, this sort of incompatibility should be relatively rare, since it would only occur during network upgrades.

**Comment by cam-schultz** [comment]
This is partially addressed by https://github.com/ava-labs/awm-relayer/issues/193, which allows the relayer to potentially still deliver a message even if a portion of the signing subnet's stake is on an incompatible version. We should still investigate adding a check at startup.

**Comment by cam-schultz** [comment]
The most straightforward catch-all would be to manually connect to peers on startup, rather than our current approach of lazily doing so on [message relay](https://github.com/ava-labs/awm-relayer/blob/main/relayer/message_relayer.go#L251). This logic does not require any information from the message being relayed itself, and should be able to be accomplished with the values in the relayer configuration.
