### ISSUE TITLE
Error downloading awm-relayer_1.0.0_darwin_amd64.tar.gz

### ISSUE THREAD

**Issue by Signor1** [ava-labs/awm-relayer#228]
**Describe the bug**
I tried deploying my avalanche subnet locally using the command `avalanche subnet deploy mySubnet` but I got this error 
`Error: failed downloading https://github.com/ava-labs/awm-relayer/releases/download/v1.0.0/awm-relayer_1.0.0_darwin_amd64.tar.gz: unexpected http status code: 404` at some point.

**To Reproduce**
In the deployment process and after the prompting of the below commands, the error pops up and stops the continuation of the deployment.
 
`using latest awm-relayer version (v1.0.0)`
`Installing AWM-Relayer v1.0.0`

Error

`Error: failed downloading https://github.com/ava-labs/awm-relayer/releases/download/v1.0.0/awm-relayer_1.0.0_darwin_amd64.tar.gz: unexpected http status code: 404`

**Expected behavior**
With the command - `avalanche subnet deploy mySubnet` I should be able to deploy my created subnet. 

**Screenshots**
<img width="1278" alt="Screenshot 2024-03-12 at 2 23 19 AM" src="https://github.com/ava-labs/awm-relayer/assets/94352660/96a51582-3fd6-4ff9-aab8-d817632d5dda">

**Operating System**
Mac OS.

**Comment by cam-schultz** [comment]
`awm-relayer` does not currently support Mac OS running on Intel processors (AKA darwin/amd64). The supported platforms are listed here: https://github.com/ava-labs/awm-relayer?tab=readme-ov-file#system-requirements

We do have a ticket to support darwin/amd64, which you can track here: https://github.com/ava-labs/awm-relayer/issues/230
