### ISSUE TITLE
Emit error on tx revert

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#236]
**Context and scope**
Transactions sent by the relayer should not revert under normal circumstances, but it doesn't hurt to emit an error to aid in debugging. Some scenarios in which the transaction may revert include:
- Bug in the message protocol contract
- Misconfigured source or destination blockchain (e.g. validators improperly registered)
- Misconfigured relayer (e.g. invalid private key)

**Discussion and alternatives**
In order to do this, we'll have to listen for the transaction to be included in a block and check the receipt status. For reference, we use this technique in many of the Teleporter and AWM Relayer end-to-end tests: https://github.com/ava-labs/teleporter/blob/8a71d0bbd121915d54792923a58d95e09bb837ba/tests/utils/utils.go#L545

**Comment by michaelkaplan13** [comment]
Once messages are processed concurrently, this transaction monitoring can be added to the `MessageHandler` after it sends a transaction to deliver a message. https://github.com/ava-labs/awm-relayer/blob/app-relayer-worker/messages/teleporter/message_handler.go#L171
