### ISSUE TITLE
Split up config.go

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#251]
**Context and scope**
`config.go` defines the entire application configuration, including sub-configurations for `SourceBlockchain`, `DestinationBlockchain`, `ManualWarpMessage`, etc. It's gotten quite large and difficult to navigate. We should split this file into multiple specialized files.

**Open questions**
It may be worth revisiting how we build nested configuration objects in `BuildConfig` as a part of this ticket. For config objects below the top level (e.g. `SourceBlockchain`) we build using `viper.UnmarshalKey`, which provides less control, and disallows setting fields via CLI or environment.

**Comment by geoff-vball** [comment]
Completed via https://github.com/ava-labs/awm-relayer/pull/302
