### ISSUE TITLE
Add API Handler for "relay message" requests

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/awm-relayer#314]
**Context and scope**
Add an API handler to the AWM relayer implementation that supports requesting the relayer relay a specific message via RPC. The relayer should looking up the message, decide if it's something that it is able to relay, and if so, initiate the `applicationRelayer` routine to relay it. This will be very helpful as a "catch-all" retry mechanism, and also allow the removal of manually configured off-chain warp messages in the future.

Currently, the relayer is only able to learn of messages to be relayed through it's listener on each source chain, or via manual configuration of off-chain warp messages. Providing an API to request a message get relayed provides a much more light weight mechanism for triggering re-tries in the event that a message is was not successfully relayed. That could occur in hypothetical situations were the message didn't include sufficient fees, or the transaction it sent previously to deliver a message revert for any reason. 

**Discussion and alternatives**
To make it easier for the API handler to route messages to the proper `ApplicationRelayer` instance (if one exists), we should likely move the logic to [get an application relayer and message handler ](https://github.com/ava-labs/awm-relayer/blob/app-relayer-worker/relayer/listener.go#L370) out of the `listener` and into a global singleton. Both the `listener` and API handler will then use that singleton to look up the application relayer / create a message handler to be used for a given message. This should pare down the `listener` to have less message handling logic also, making it easier to reason about. 

**Open questions**
- What are the required/option RPC params? Current thinking is:
    - Required: source subnet ID, warp message ID
    - Optional: block number message was sent in 
- Flag to enable/disable the API?
- Documentation around potential DOS vectors of the API should it be open to the public networking wise?
- Should any authentication be required? Probably makes sense to recommend it is only an RPC available locally.

**Comment by cam-schultz** [comment]
Relevant ticket: https://github.com/ava-labs/awm-relayer/issues/171
