### ISSUE TITLE
Make e2e tests exit cleanly 

### ISSUE THREAD

**Issue by iansuvak** [ava-labs/awm-relayer#380]
**Context and scope**
Currently when e2e tests don't exit cleanly, due to some failures or due to being interrupted by user, the avalanchego processes spun up by `tmpnet` stay alive and prevent re-running tests.  We should make sure that tests clean up after themselves and are ready for another run regardless of status of previously aborted/failed tests.

**Comment by geoff-vball** [comment]
We should investigate running the whole test suite in a docker container, which would get us the cleanup for free.
