### ISSUE TITLE
Small Warp Signature API Standardization Items

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/awm-relayer#381]
**Context and scope**
#361 introduces the scaffolding for fetching an arbitrary aggregate signature via API request. There a handful of small clean up items that will bring its initial implementation more inline with our other API standards:
- [ ] Raw message should be hexadecimal encoded in request (with optional 0x prefix). We generally have not used base64 encoding anywhere.
- [ ] Response body fields should also be hexadecimal encoded
- [ ] Error responses can be descriptive strings, but shouldn't expose internal errors. Error responses should also be HTTP 200s, with JSON response body that includes the error message.
- [ ] Avoid pointer usage for `uint`s / `ids.ID`s where not strictly necessary
- [ ] Responses should have `application/JSON` header
- [ ] Consider having the response only include the aggregate signature and bit vector rather than the full signed message.

**Comment by michaelkaplan13** [comment]
> Should all responses have application/JSON header?
Yes, all responses from the application (including errors) should be JSON.

> We have one in signature aggregation request, for the quorum numerator, because it's optional.
IMO, we should avoid it. It leads to having to check for nil wherever used, and greatly increases the chances of an bug if we miss that check. If it's not included in the request, it will default to 0, and can be handled properly from there.

**Comment by iansuvak** [comment]
Closing this issue since it's merged into the feature branch
