### ISSUE TITLE
Use ACP-118 interface

### ISSUE THREAD

**Issue by iansuvak** [ava-labs/awm-relayer#383]
**Context and scope**
Once [ACP-118](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/118-warp-signature-request) has been implemented we need to switch our `AppRequests` to use the new format as well as expose the `justification` field in the `raw-message` interface 

**Discussion and alternatives**

**Open questions**

**Comment by michaelkaplan13** [comment]
This should now be unblocked with the Subnet EVM implementation of the ACP-118 handlers added in this PR: https://github.com/ava-labs/subnet-evm/pull/1260/files
