### ISSUE TITLE
Add protobuf lint job

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/awm-relayer#402]
**Context and scope**
We should check in CI that any protobuf definition changes have been properly linted. Example: https://github.com/ava-labs/avalanchego/blob/master/.github/workflows/ci.yml#L129

**Comment by feuGeneA** [comment]
We do already check in `scripts/lint.sh`, which is run by CI.

**Comment by cam-schultz** [comment]
Ah, yeah we do. I'll close this issue out. @najeal thanks for hopping on this issue, and apologies for the confusion.
