### ISSUE TITLE
Cleanup relayer gas calculation

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/awm-relayer#5]
**Context and scope**
We pass in a calculated gas amount and noticed the transaction would revert on destination teleport contract because of not enough gas. Currently we are using `ReceiveCrossChainMessageStaticGasCost` which should be warp's `getVerifiedWarpMessage` gas cost now, and no longer have `ReceiveCrossChainMessageGasCostPerAggregatedKey` in the precompile

[TODO](https://github.com/ava-labs/awm-relayer/blob/main/utils/utils.go#L21)

**Comment by cam-schultz** [comment]
Fixed by https://github.com/ava-labs/teleporter/pull/320
