### ISSUE TITLE
GLIBC_2.32 not found error when running AWM Relayer on Ubuntu 20.04

### ISSUE THREAD

**Issue by Mtsurve** [ava-labs/awm-relayer#503]
**Bug Description:**
When running `awm-relayer_1.4.0_linux_amd64.tar.gz` on my GCP machine with Ubuntu 20.04, I encountered an error regarding the GLIBC version.

**Error Message:**

**Machine Information:**
- OS: Ubuntu 20.04
- GLIBC Version: 2.31 (Output of `ldd --version` shows `ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31`)
- Hosting: Google Cloud Platform (GCP)

**Steps to Reproduce:**
1. Download `awm-relayer_1.4.0_linux_amd64.tar.gz`.
2. Extract the tar file.
3. Run the command to execute `awm-relayer`.

**Expected Behavior:**
The relayer should execute without error.

**Actual Behavior:**
The relayer fails to execute with an error indicating that GLIBC_2.32 is required.

**Possible Solution:**
- Provide a compatible binary for Ubuntu 20.04 (with GLIBC 2.31).
- Or, document the minimum system requirements clearly for running the AWM Relayer.

**Additional Context:**
This error is likely due to a version mismatch between the GLIBC on my server and the GLIBC version required by the AWM Relayer.

**Comment by cam-schultz** [comment]
Hi @Mtsurve , awm-relayer supports Ubuntu 22.04 and later. Ubuntu 20.04 is untested, and is not expected to work without modification. Please see the system requirements here: https://github.com/ava-labs/awm-relayer/blob/main/relayer/README.md#system-requirements.
