### ISSUE TITLE
Get Quorum numerator/denominator from VM

### ISSUE THREAD

**Issue by minghinmatthewlam** [ava-labs/awm-relayer#8]
**Context and scope**
Warp quorum numerator and denominators are set to decide what signature threshold needs to be exceeded to count as a valid warp message.

The quorum numerator and denominator are provided as a warp precompile config in the genesis. We should use those values rather than the ones hardcoded in the relayer.

https://github.com/ava-labs/awm-relayer/blob/main/utils/utils.go#L18

**Comment by cam-schultz** [comment]
We can get the Warp numerator specified in genesis using `eth_getChainConfig` and parsing `warpConfig.quorumNumerator`. The Warp denominator is fixed to 100 for `subnet-evm` and `coreth`, but for robustness we may want to attempt to parse that value as well and default to 100 if the value doesn't exist.
